create table if not exists public.product_ratings (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  reviewer_id text not null,
  reviewer_name text,
  rating integer not null check (rating between 1 and 5),
  feedback text,
  created_at timestamptz not null default now(),
  unique (product_id, reviewer_id)
);

alter table public.product_ratings
add column if not exists feedback text;

alter table public.product_ratings
add column if not exists reviewer_name text;

alter table public.product_ratings enable row level security;

drop policy if exists "Anyone can view product ratings" on public.product_ratings;
drop policy if exists "Anyone can submit product ratings" on public.product_ratings;
drop policy if exists "Anyone can update their product ratings" on public.product_ratings;

create policy "Anyone can view product ratings"
on public.product_ratings for select
to anon, authenticated
using (true);

create policy "Anyone can submit product ratings"
on public.product_ratings for insert
to anon, authenticated
with check (true);

create policy "Anyone can update their product ratings"
on public.product_ratings for update
to anon, authenticated
using (true)
with check (true);
